#!/bin/bash

#########################
#Space-seperated list of archs e.g export ARCHS=("armv7 armv7s arm64 i386 x86_64")
export ARCHS=("x86_64")
export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
export DEVFOLDER="/Applications/Xcode.app/Contents/Developer"
# an SDK prior to 6.0 is required if the target ARCH is armv6
SDK_VERSION="7.1"
PARALLEL_NUM=1

CURL_VERSION=7.35.0
LIBEVENT_VERSION="2.0.21-stable"
OPENSSL_VERSION=1.0.1f
TRANSMISSION_VERSION=2.82

#########################

if [ -z ${ARCH} ]; then ARCH="system"; fi