#!/bin/bash

#########################
#Space-seperated list of archs e.g export ARCHS=("armv7 armv7s arm64 i386 x86_64")
export ARCH=x86_64
export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
export DEVFOLDER="/Applications/Xcode.app/Contents/Developer"
# an SDK prior to 6.0 is required if the target ARCH is armv6
SDK_VERSION=“9.3”
PARALLEL_NUM=4

CURL_VERSION=7.50.0
LIBEVENT_VERSION="2.0.22-stable"
OPENSSL_VERSION=1.0.2h
TRANSMISSION_VERSION=2.92

#########################

if [ -z ${ARCH} ]; then ARCH="system"; fi